name: Versionament
inputs:
  paths:
    description: 'Paths to verify content'
    required: true

outputs:
  content:
    value: ${{ steps.generate_hash.outputs.content }}
    description: 'Content Hash'

runs:
  using: composite
  steps:

  - name: Checkout script repository
    uses: actions/checkout@v4
    with:
      repository: 'tecmise/actions'
      path: code

  - id: generate_hash
    name: Generate JWT and get access token
    shell: bash
    run: |
      hash=$(python code/.github/scripts/content_check.py "${{ inputs.paths }}")
      echo "content=$hash" >> $GITHUB_OUTPUT
