name: Expose Endpoints in API Gateway
inputs:
  routes_file:
    description: 'Caminho do arquivo JSON de configuração das rotas para API Gateway'
    required: false
    default: ''
  aws_region:
    description: "'AWS Region to deploy the API Gateway'"
    required: false
    default: 'us-east-1'
  bucket_name:
    description: "'S3 Bucket name for Terraform state'"
    required: true

runs:
  using: composite
  steps:
    - name: Create Folder for API Gateway
      shell: bash
      run: mkdir -p ${{ github.run_number }}

    - name: Copy Routes File
      shell: bash
      run: |
        if [ -n "${{ inputs.routes_file }}" ]; then
          cp "${{ inputs.routes_file }}" ${{ github.run_number }}/routes.json
        else
          echo "No routes file provided, skipping copy."
        fi


    - name: Execute API Gateway Script
      shell: bash
      working-directory: ${{ github.run_number }}
      run: |       
        # Executa o script Python com o JSON como argumento
        python ${{ github.action_path }}/../../scripts/terraform/api-gateway.py "$(cat routes.json)"
        ls -ltra

    - name: Creating other files
      shell: bash
      working-directory: ${{ github.run_number }}
      run: |       
        echo 'provider "aws" {' > provider.tf
        echo '  region = ${{ inputs.aws_region }}' >> provider.tf
        echo '}' >> provider.tf
        echo 'terraform {' > backend.tf
        echo '  required_providers {' >> backend.tf
        echo '    aws = {' >> backend.tf
        echo '      source  = "hashicorp/aws"' >> backend.tf
        echo '      version = "5.81.0"' >> backend.tf
        echo '    }' >> backend.tf
        echo '  }' >> backend.tf
        echo '  backend "s3" {' >> backend.tf
        echo '    key            = "api-gateway-routes/${{ github.event.repository.name }}.tfstate"' >> backend.tf
        echo '    bucket         = "${{ inputs.bucket_name }}"' >> backend.tf
        echo '    region         = "us-east-1"' >> backend.tf
        echo '  }' >> backend.tf
        echo '}' >> backend.tf
        
        echo 'variable root_resource_id {' >> variable.tf
        echo '  type = string' >> variable.tf
        echo '}' >> variable.tf
        echo 'variable rest_api_id {' >> variable.tf
        echo '  type = string' >> variable.tf
        echo '}' >> variable.tf
        echo 'variable invoke_uri {' >> variable.tf
        echo '  type = string' >> variable.tf
        echo '}' >> variable.tf
        echo 'variable authorizer_id {' >> variable.tf
        echo '  type = string' >> variable.tf
        echo '}' >> variable.tf
        echo 'variable cors_origin_domain {' >> variable.tf
        echo '  type = string' >> variable.tf
        echo '}' >> variable.tf
        
        
    - name: Upload API Gateway Files
      uses: actions/upload-artifact@v4
      with:
        name: api-gateway-files
        path: ${{ github.run_number }}
        
