name: Expose Endpoints in API Gateway
inputs:
  routes_file:
    description: 'Caminho do arquivo JSON de configuração das rotas para API Gateway'
    required: false
    default: ''


runs:
  using: composite
  steps:
    - name: Create Folder for API Gateway
      shell: bash
      run: mkdir -p ${{ github.run_number }}


    - name: Execute API Gateway Script
      shell: bash
      working-directory: ${{ github.run_number }}
      run: |       
        # Executa o script Python com o JSON como argumento
        python ${{ github.action_path }}/../../scripts/terraform/api-gateway.py "$(cat ${{ inputs.routes_file }})"
        ls -ltra