name: Expose Endpoints in API Gateway
inputs:
  routes:
    description: 'Context for running the action (e.g., ubuntu-latest or a self-hosted label)'
    required: false
    default: 'ubuntu-latest'

runs:
  using: composite
  steps:
    - name: Get Endpoints value
      shell: bash
      run: |
        echo "${{ inputs.routes }}"


    - name: Convert Data
      shell: bash
      run: |
        CONTENT=$("${{ inputs.routes }}" | jq .)
        echo "Content: ${CONTENT}"

    - name: Execute API Gateway Script
      shell: bash
      run: |
        CONTENT=$("${{ inputs.routes }}" | jq .)
        python ${{ github.action_path }}/../../scripts/terraform/api-gateway.py '${CONTENT}'
        ls -ltra