name: Expose Endpoints in API Gateway
inputs:
  endpoints:
    description: 'Context for running the action (e.g., ubuntu-latest or a self-hosted label)'
    required: false
    default: 'ubuntu-latest'

runs:
  using: composite
  steps:
    - id: show value
      name: Get Endpoints value
      shell: bash
      run: |
        echo "${{ inputs.endpoints }}"


    - name: Convert Data
      shell: bash
      run: |
        echo "${{ inputs.endpoints }}" | jq .