name: Expose Endpoints in API Gateway
inputs:
  routes:
    description: 'JSON contendo as rotas para API Gateway'
    required: true

runs:
  using: composite
  steps:
    - name: Execute API Gateway Script
      shell: bash
      run: |
        python ${{ github.action_path }}/../../scripts/terraform/api-gateway.py '${{ inputs.routes }}'
        ls -ltra