name: Expose Endpoints in API Gateway
inputs:
  routes:
    description: 'Context for running the action (e.g., ubuntu-latest or a self-hosted label)'
    required: false
    default: 'ubuntu-latest'

runs:
  using: composite
  steps:

    - name: Execute API Gateway Script
      shell: bash
      run: |
        python ${{ github.action_path }}/../../scripts/terraform/api-gateway.py --routes '${{ inputs.routes }}'
        ls -ltra

