name: Expose Endpoints in API Gateway
inputs:
  routes:
    description: 'JSON de configuração das rotas para API Gateway'
    required: true

runs:
  using: composite
  steps:
    - name: Get Endpoints value
      shell: bash
      run: |
        echo '${{ inputs.routes }}'

    - name: Execute API Gateway Script
      shell: bash
      run: |
        # Salva o JSON em um arquivo temporário para preservar formatação
        echo '${{ inputs.routes }}' > /tmp/routes.json
        
        # Executa o script Python com o JSON como argumento
        python ${{ github.action_path }}/../../scripts/terraform/api-gateway.py "$(cat /tmp/routes.json)"
        
        # Lista os arquivos gerados
        ls -ltra