name: Discord Notifier File
inputs:
  discord-webhook-url:
    description: 'URL do webhook do Discord (opcional, usa o segredo se não fornecido)'
    required: true
  file-path:
    description: 'Caminho para o arquivo que será enviado (opcional)'
    required: false

runs:
  using: composite
  steps:
  - name: Notify Discord Webhook
    shell: bash
    run: curl -X POST ${{ inputs.discord-webhook-url }} -F "file=@${{ inputs.file-path }}"