name: Running On
inputs:
  context:
    description: 'Context for running the action (e.g., ubuntu-latest or a self-hosted label)'
    required: false
    default: 'ubuntu-latest'
  arm64:
    description: 'Set to "true" to run on ARM64 self-hosted architecture'
    required: false
    default: 'false'

outputs:
  runs_on:
    value: ${{ steps.determine_runner.outputs.runs_on }}
    description: 'The final runs-on value, either a string or a JSON array string.'

runs:
  using: composite
  steps:
    - id: determine_runner
      name: Determine runner environment
      shell: bash
      run: |
        # 1. Verifica se é um runner padrão do GitHub
        if [[ "${{ inputs.context }}" == "ubuntu-latest" || "${{ inputs.context }}" == "windows-latest" || "${{ inputs.context }}" == "macos-latest" ]]; then
          echo "runs_on=${{ inputs.context }}" >> $GITHUB_OUTPUT
        else
          # 2. Se não for, monta a lista de tags para runner self-hosted
          RUNNER_TAGS="['${{ github.ref_name }}', '${{ inputs.context }}', 'self-hosted', 'linux'"
          
          # 3. Adiciona a tag de arquitetura condicionalmente
          if [[ "${{ inputs.arm64 }}" == "true" ]]; then
            RUNNER_TAGS="$RUNNER_TAGS, 'arm64'"
          else
            RUNNER_TAGS="$RUNNER_TAGS, 'x64'"
          fi
          
          RUNNER_TAGS="$RUNNER_TAGS, 'amazon']"
          echo "runs_on=$RUNNER_TAGS" >> $GITHUB_OUTPUT
        fi

    - name: Show Values
      shell: bash
      run: echo "${{ steps.determine_runner.outputs.runs_on }}"

