name: Authenticate Aws Account
inputs:
  aws_accounts:
    description: 'Accounts'
    required: true
  category:
    description: 'Category of repository'
    required: true
  aws_region:
    description: 'Region'
    required: false
    default: 'us-east-1'

runs:
  using: composite
  steps:

  - name: configure aws credentials-s4s
    uses: aws-actions/configure-aws-credentials@v4
    if: ${{ inputs.category == 's4s' && (github.ref_name == 'main' || github.ref_name == 'master' || github.ref_name == 'sandbox') }}
    with:
      role-to-assume: arn:aws:iam::${{ fromJson(inputs.aws_accounts).s4s[github.ref_name] }}:role/github-actions-role
      role-session-name: github-actions-role
      aws-region: ${{ inputs.aws_region }}

  - name: configure aws credentials-infrastructure
    uses: aws-actions/configure-aws-credentials@v4
    if: ${{ inputs.category == 'infrastructure' && (github.ref_name == 'main' || github.ref_name == 'master') }}
    with:
      role-to-assume: arn:aws:iam::${{ fromJson(inputs.aws_accounts).infrastructure }}:role/github-actions-role
      role-session-name: github-actions-role
      aws-region: ${{ inputs.aws_region }}