name: Authenticate Aws Account
inputs:
  aws_accounts:
    description: 'Accounts'
    required: true
  category:
    description: 'Category of repository'
    required: true

outputs:
  content:
    value: ${{ steps.generate_hash.outputs.content }}
    description: 'Content Hash'

runs:
  using: composite
  steps:

  - name: Show category
    shell: bash
    run: "echo 'Ref: ${{ github.ref_name }} Category: ${{ inputs.category }}'"

  - name: configure aws credentials s4s
    if: ${{ inputs.category == 's4s' && (github.ref_name == 'main' || github.ref_name == 'master' || github.ref_name == 'sandbox') }}
    shell: bash
    run: |
      echo "${{ fromJson(inputs.aws_accounts).s4s[github.ref_name] }}"

  - name: configure aws credentials infrastructure
    if: ${{ inputs.category == 'infrastructure' && (github.ref_name == 'main' || github.ref_name == 'master') }}
    shell: bash
    run: |
      echo "${{ fromJson(inputs.aws_accounts).infrastructure }}"
