name: Terraform Init
inputs:
  artifact:
    description: 'Artifact'
    required: true
  bucket:
    description: 'Terraform S3 Bucket'
    required: true
  key:
    description: 'Terraform S3 Key'
    required: true
runs:
  using: composite
  steps:

  - uses: actions/setup-node@v4
    with:
      node-version: '20'
  - uses: hashicorp/setup-terraform@v3

  - name: Show Files
    shell: bash
    run: |
      ls -ltra 

  - name: Terraform Init
    shell: bash
    run: |
      terraform init -backend-config=bucket=${{ inputs.bucket }} -backend-config=key=${{ inputs.key }}

  - name: Upload Node Group
    uses: actions/upload-artifact@v4
    with:
      path: '.'
      name: ${{ inputs.name }}
      include-hidden-files: 'true'
      retention-days: 7