name: Terraform Init
inputs:
  artifact:
    description: 'Artifact'
    required: true
  bucket:
    description: 'Terraform S3 Bucket'
    required: true
  key:
    description: 'Terraform S3 Key'
    required: true
  working_directory:
    description: 'Working Directory'
    required: false
    default: '.'
runs:
  using: composite
  steps:

  - uses: actions/setup-node@v4
    with:
      node-version: '20'
  - uses: hashicorp/setup-terraform@v3

  - name: Show Files
    working-directory: ${{ inputs.working_directory }}
    shell: bash
    run: |
      ls -ltra 

  - name: Terraform Init
    shell: bash
    working-directory: ${{ inputs.working_directory }}
    run: |
      terraform init -backend-config=bucket=${{ inputs.bucket }} -backend-config=key=${{ inputs.key }}

#  - name: Upload Node Group
#    uses: actions/upload-artifact@v4
#    with:
#      path: '${{ inputs.working_directory }}'
#      name: ${{ inputs.artifact }}
#      include-hidden-files: 'true'
#      retention-days: 7

  - name: Upload Generated Files
    uses: tecmise/actions/.github/actions/upload-artifact@v6.3.0
    with:
      path: '${{ inputs.working_directory }}'
      aws_accounts: ${{ vars.AWS_ACCOUNTS }}
      artifact: '${{ inputs.artifact }}'


  - name: Summary - Inputs do Terraform Init
    shell: bash
    run: |
      {
        echo "## Terraform Init - Inputs"
        echo
        echo "| Input | Valor |"
        echo "|---|---|"
        echo "| artifact | \`${{ inputs.artifact }}\` |"
        echo "| bucket | \`${{ inputs.bucket }}\` |"
        echo "| key | \`${{ inputs.key }}\` |"
        echo "| working_directory | \`${{ inputs.working_directory }}\` |"
      } >> "$GITHUB_STEP_SUMMARY"