name: Upload Artifact
inputs:
  aws_accounts:
    description: 'Accounts'
    required: true
  category:
    description: 'Category of repository'
    required: false
    default: 'infrastructure'
  aws_region:
    description: 'Region'
    required: false
    default: 'us-east-1'
  path:
    description: 'Path to the artifact to be uploaded'
    required: true

runs:
  using: composite
  steps:

  - name: configure aws credentials-s4s
    uses: aws-actions/configure-aws-credentials@v4
    if: ${{ inputs.category == 's4s' && (github.ref_name == 'main' || github.ref_name == 'master' || github.ref_name == 'sandbox') }}
    with:
      role-to-assume: arn:aws:iam::${{ fromJson(inputs.aws_accounts).s4s[github.ref_name] }}:role/github-actions-role
      role-session-name: github-actions-role
      aws-region: ${{ inputs.aws_region }}

  - name: configure aws credentials-infrastructure
    uses: aws-actions/configure-aws-credentials@v4
    if: ${{ inputs.category == 'infrastructure' }}
    with:
      role-to-assume: arn:aws:iam::${{ fromJson(inputs.aws_accounts).infrastructure }}:role/github-actions-role
      role-session-name: github-actions-role
      aws-region: ${{ inputs.aws_region }}

  - name: Upload artifact to S3
    shell: bash
    run: |
      aws s3 ls

  - name: Remove Aws Credentials
    shell: bash
    if: always()
    run: |
      rm -rf ~/.aws/credentials
      rm -rf ~/.aws/config
