name: Download Dependencies

on:
  workflow_call:
    inputs:
      runner_name:
        type: string
        default: 'building'
      runner_category:
        type: string
        default: 's4s'
      go_version:
        type: string
        default: '^1.21'

jobs:

  building:
    name: Building
    environment: ${{ github.ref_name }}
    runs-on: tecmise-runner
    permissions:
      contents: read
      id-token: write
    env:
      GO111MODULE: on
      GOPROXY: direct
      GOSUMDB: off
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go_version }}
        cache: false

    - name: Autenticar repositórios privados
      run: |
        # Cria ~/.netrc com credenciais GitHub
        echo "machine github.com login ${{ github.actor }} password ${{ secrets.CONNECTORS_KEY }}" > ~/.netrc
        chmod 600 ~/.netrc
        go env -w GOPRIVATE=github.com/tecmise/*
        go env -w GOSUMDB=off

    - name: Authenticate on AWS
      uses: tecmise/actions/.github/actions/aws-authenticate@main
      with:
        category: 'infrastructure'
        aws_accounts: ${{ vars.AWS_ACCOUNTS }}
        aws_region: us-east-1

    - name: Verify AWS credentials
      run: aws sts get-caller-identity

    - name: Check S3 cache
      id: check_s3
      uses: tecmise/actions/.github/actions/check-artifact-exists@main
      with:
        category: 'infrastructure'
        aws_region: us-east-1
        artifact: go-deps

    - name: Create folder
      if: steps.check_s3.outputs.exists == 'false'
      run: mkdir -p ~/go/pkg/mod

    - name: Tidy
      if: steps.check_s3.outputs.exists == 'false'
      run: go mod tidy

    - name: Download dependencies
      if: steps.check_s3.outputs.exists == 'false'
      run: go mod download

    - name: MoveFiles
      if: steps.check_s3.outputs.exists == 'false'
      run: |
        mkdir ${{ github.sha }}
        chmod -R u+w ~/go/pkg/mod
        mv ~/go/pkg/mod/* ${{ github.sha }}/

    - name: Upload files
      if: steps.check_s3.outputs.exists == 'false'
      uses: tecmise/actions/.github/actions/upload-artifact@main
      with:
        category: 'infrastructure'
        aws_region: us-east-1
        artifact: go-deps
        path: ${{ github.sha }}

