name: "Validate Source Code"
on:
  workflow_call:
    secrets:
      DISCORD_NOTIFIER_URL:
        required: true
      CONNECTORS_KEY:
        required: true

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    environment: master
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.21'
          cache: false

      - name: Configure Go env for private modules
        run: go env -w GOPRIVATE=github.com/tecmise

      - name: Instead of config
        run: git config --global url."https://oauth2:${{ secrets.CONNECTORS_KEY }}@github.com/".insteadOf "https://github.com/"

      - name: Tidy
        run: go mod tidy

      - name: Download dependencies
        run: go mod download

      - name: Build Container
        run: |
          go mod verify
          go mod vendor

      - name: Verificar erros de compilação
        run: go build ./...

      - name: Verificar erros de lint
        uses: golangci/golangci-lint-action@v8
        with:
          verify: false

  open-pr:
    name: Open PR
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    needs: validate
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Criar Pull Request via GitHub CLI
      id: create_pr
      run: |
        # Obter a data atual
        CURRENT_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    
        # Criar o corpo da PR
        PR_BODY="## 🚀 Uma nova versão do connector está sendo gerada
    
        ### Nova versao patch será gerada
    
        Por padrão, uma nova versão patch será gerada. Se você deseja alterar o tipo de versão (major, minor, patch), por favor, realizar um comentario nesta PR com a palavra-chave correspondente:
        - \`#major\` para uma nova versão major
        - \`#minor\` para uma nova versão minor
        - \`#patch\` para uma nova versão patch
    
        ---
        *Gerado por GitHub Actions em ${CURRENT_DATE}*"
    
        # Criar a PR sem a flag --json e capturar a URL diretamente
        PR_URL=$(gh pr create -B master -H delivery/master \
          --title "🔗 New connector version" \
          --body "$PR_BODY")
    
        echo "PR_URL=$PR_URL" >> $GITHUB_OUTPUT
        
        # Extrair o número do PR da URL usando expressão regular
        PR_NUMBER=$(echo $PR_URL | sed -E 's|.*/([0-9]+)$|\1|')
        echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
    
        echo "Pull Request criado: $PR_URL (PR #$PR_NUMBER)"
      env:
        GH_TOKEN: ${{ secrets.CONNECTORS_KEY }}

    - name: Notify
      uses: tecmise/actions/.github/actions/discord-notifier@v3.0.4
      with:
        title: '🔗 Nova Pull request no connector 🔗'
        message: 'Uma nova versão do connector está sendo gerada. Caso seja necessario alterar o tipo de versão (major, minor, patch), por favor, realizar um comentário na PR com a palavra-chave correspondente.'
        severity: 'info'
        discord-webhook-url: "${{ secrets.DISCORD_NOTIFIER_URL }}"

  notify-error:
    name: Notify Error
    runs-on: ubuntu-latest
    needs: validate
    if: ${{ always() && needs.validate.result == 'failure' }}
    environment: "${{ github.ref_name }}"
    steps:
      - name: Send Notification Error
        uses: tecmise/actions/.github/actions/discord-notifier@v3.0.4
        with:
          title: '🚨 Falha ao validar connector 🚨'
          message: "houve uma falha no build do connector"
          severity: 'error'
          discord-webhook-url: "${{ secrets.DISCORD_NOTIFIER_URL }}"
          fields:
            Link:"${{github.workflow.url}}"
            Run:"${{github.run_id}}"
