name: "Validate Source Code"
on:
  workflow_call:
    secrets:
      CONNECTORS_KEY:
        required: true
      DISCORD_NOTIFIER_URL:
        required: true

jobs:
  validate:
    name: Validate
    runs-on: ['infrastructure', 's4s', "self-hosted", "linux", "x64", "amazon"]
    environment: master
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.21'
          cache: false

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Configure Go env for private modules
        run: go env -w GOPRIVATE=github.com/tecmise

      - name: Instead of config
        run: git config --global url."https://oauth2:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Tidy
        run: go mod tidy

      - name: Download dependencies
        run: go mod download

      - name: Build Container
        run: |
          go mod verify
          go mod vendor

  open-pr:
    name: Open PR
    environment: ${{ github.ref_name }}
    runs-on: ['infrastructure', 's4s', "self-hosted", "linux", "x64", "amazon"]
    needs: validate
    steps:


    - name: Create Pull Request via API
      uses: actions/github-script@v6
      id: create_pr
      with:
        github-token: ${{ secrets.CONNECTORS_KEY }}
        result-encoding: json
        script: |
          const currentDate = new Date().toISOString();
          
          const prBody = `## 🚀 Uma nova versão do connector está sendo gerada
          
          ### Nova versao patch será gerada
          
          Por padrão, uma nova versão patch será gerada. Se você deseja alterar o tipo de versão (major, minor, patch), por favor, realizar um comentario nesta PR com a palavra-chave correspondente:
          - \`#major\` para uma nova versão major
          - \`#minor\` para uma nova versão minor
          - \`#patch\` para uma nova versão patch
          
          ---
          *Gerado por GitHub Actions em ${currentDate}*`;
          
          const { data: pullRequest } = await github.rest.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "🔗 New connector version",
            body: prBody,
            head: "delivery/master",
            base: "master"
          });
          
          console.log(`Pull Request criado: ${pullRequest.html_url} (PR #${pullRequest.number})`);

          return {
            prUrl: pullRequest.html_url,
            prNumber: pullRequest.number
          };

    - name: Notify
      uses: tecmise/actions/.github/actions/discord-notifier@v3.0.4
      with:
        title: '🔗 Nova Pull request no connector 🔗'
        message: 'Uma nova versão do connector está sendo gerada. Caso seja necessario alterar o tipo de versão (major, minor, patch), por favor, realizar um comentário na PR com a palavra-chave correspondente.'
        severity: 'info'
        discord-webhook-url: "${{ secrets.DISCORD_NOTIFIER_URL }}"

  notify-error:
    name: Notify Error
    runs-on: ['infrastructure', 's4s', "self-hosted", "linux", "x64", "amazon"]
    needs: validate
    if: ${{ always() && needs.validate.result == 'failure' }}
    environment: "${{ github.ref_name }}"
    steps:
      - name: Send Notification Error
        uses: tecmise/actions/.github/actions/discord-notifier@v3.0.4
        with:
          title: '🚨 Falha ao validar connector 🚨'
          message: "houve uma falha no build do connector"
          severity: 'error'
          discord-webhook-url: "${{ secrets.DISCORD_NOTIFIER_URL }}"
          fields:
            Link:"${{github.workflow.url}}"
            Run:"${{github.run_id}}"
