name: Checking Changes

on:
  workflow_call:
    outputs:
      has_changes:
        value: ${{ jobs.checking-last-version.outputs.has_changes }}
        description: 'Content Hash'
      hashcode:
        value: ${{ jobs.loading-hash.outputs.content }}
        description: 'Content Hash'

jobs:
  loading-hash:
    name: Generating hashcode
    runs-on: ubuntu-latest
    outputs:
      content: ${{ steps.generate_hash.outputs.content }}
    steps:

    - name: Checkout script repository
      uses: actions/checkout@v4
      with:
        repository: 'tecmise/actions'
        path: code

    - id: generate_hash
      name: Generate Hash Token
      run: |
        
        JSON_CONFIG=$(cat << EOF
        {
          "ignore_path": ["terraform", ".github", ".idea", ".git", ".gitignore"],
          "source": "."
        }
        EOF
        )
        hash=$(python code/.github/scripts/md5_calculator.py "$JSON_CONFIG")
        echo "Generated hash: $hash"
        echo "content=$hash" >> $GITHUB_OUTPUT

    - name: Remove code directory
      run: rm -rf code

  checking-last-version:
    name: Checking current version
    runs-on: ubuntu-latest
    needs: loading-hash
    outputs:
      has_changes: ${{ steps.check_version.outputs.has_changes }}
    steps:

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ fromJson(vars.AWS_ACCOUNTS).s4s[github.ref_name] }}:role/github-actions-role
        role-session-name: github-actions-role
        aws-region: 'us-east-1'

    - name: "Get parameters from SSM"
      id: last_version
      run: |
        # Salvar a saída do comando em um arquivo
        aws ssm get-parameters-by-path --path "/versions/${{ github.event.repository.name }}" --region us-east-1 > parameters.json
        
        # Exibir o conteúdo para debug
        cat parameters.json
        
        # Escapar corretamente o conteúdo para o GITHUB_OUTPUT
        # Usando a sintaxe de delimitador para valores multilinhas do GitHub Actions
        echo "content<<EOF" >> $GITHUB_OUTPUT
        cat parameters.json >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT


    - name: "Check if parameters are empty or different from hash"
      id: check_version
      run: |
        CURRENT_HASH="${{ steps.generate_hash.outputs.content }}"
        echo "Current hash: $CURRENT_HASH"
        
        # Construir o nome completo do parâmetro que estamos procurando
        PARAM_NAME="/versions/${{ github.event.repository.name }}/hashcode"
        echo "Looking for parameter: $PARAM_NAME"
        
        # Verificar se o parâmetro existe usando jq
        PARAM_EXISTS=$(jq --arg name "$PARAM_NAME" '.Parameters[] | select(.Name == $name) | length' parameters.json 2>/dev/null || echo "0")
        
        if [ "$PARAM_EXISTS" == "0" ] || [ -z "$PARAM_EXISTS" ]; then
          echo "Parameter $PARAM_NAME not found, setting has_changes=true"
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          # Obter o valor do parâmetro específico
          PARAM_VALUE=$(jq --arg name "$PARAM_NAME" -r '.Parameters[] | select(.Name == $name) | .Value' parameters.json)
          echo "Parameter value: $PARAM_VALUE"
          
          # Comparar com o hash atual
          if [ "$PARAM_VALUE" == "$CURRENT_HASH" ]; then
            echo "No changes detected, setting has_changes=false"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected, setting has_changes=true"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
        fi